// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu5Xow8q0lP_5Kfa14ofmhJ0BiXmOYgMI',
    appId: '1:774639674582:web:f0f2ab32e3653f8ba29577',
    messagingSenderId: '774639674582',
    projectId: 'lab10-4-firebase',
    authDomain: 'lab10-4-firebase.firebaseapp.com',
    storageBucket: 'lab10-4-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbVedsbZEEn2b0N_shkGieVanagEiIXnE',
    appId: '1:774639674582:android:266e792e2b1e110ba29577',
    messagingSenderId: '774639674582',
    projectId: 'lab10-4-firebase',
    storageBucket: 'lab10-4-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLBo_DeEjAJjO1bdnjD1JygcBc0lWodYI',
    appId: '1:774639674582:ios:71f13687283aa0c6a29577',
    messagingSenderId: '774639674582',
    projectId: 'lab10-4-firebase',
    storageBucket: 'lab10-4-firebase.firebasestorage.app',
    iosBundleId: 'com.example.lab104',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLBo_DeEjAJjO1bdnjD1JygcBc0lWodYI',
    appId: '1:774639674582:ios:71f13687283aa0c6a29577',
    messagingSenderId: '774639674582',
    projectId: 'lab10-4-firebase',
    storageBucket: 'lab10-4-firebase.firebasestorage.app',
    iosBundleId: 'com.example.lab104',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu5Xow8q0lP_5Kfa14ofmhJ0BiXmOYgMI',
    appId: '1:774639674582:web:db60be4d4cadc798a29577',
    messagingSenderId: '774639674582',
    projectId: 'lab10-4-firebase',
    authDomain: 'lab10-4-firebase.firebaseapp.com',
    storageBucket: 'lab10-4-firebase.firebasestorage.app',
  );
}
