name: lab10_full
description: "A final integrated project for Lab 10"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
